#===============================================================
#   Description: dein_lazy.toml
#   Author: N-Shinoda
#   Last Modified: 2019-08-28
#===============================================================

#===============================================================
# Shougo/deoplete.nvim
# 自動補完システム(dark powered neo-completion)
#===============================================================
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
on_event = 'InsertEnter'
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''

#===============================================================
# zchee/deoplete-clang
# deopleteの補完ソース
#===============================================================
[[plugins]]
repo = 'zchee/deoplete-clang'

#===============================================================
# Shougo/neoinclude.vim
# ヘッダファイルの補完
#===============================================================
[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']

#===============================================================
# Shougo/neosnippet.vim
# スニペット機能を追加
#===============================================================
[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

#===============================================================
# rhysd/vim-clang-format
# C/C++の入力補完をしてくれるプラグイン
#===============================================================
[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = 'cpp'

